version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    exclude-paths:
      # ignore package.json (and lockfile) directly in /examples
      - "examples/angular11/package.json"
      - "examples/angula11/package-lock.json"
      - "examples/angular17/package.json"
      - "examples/angula17/package-lock.json"
      # ignore all other examples subfolders
      - "examples/*/**"